### ISSUE TITLE
[Bug] - No test details displayed

### ISSUE THREAD

**Issue by mulholio** [Raathigesh/majestic#117]
When running Majestic, the list of tests is displayed but their content is blank:

![image](https://user-images.githubusercontent.com/20966690/55717097-7915b680-59f0-11e9-9485-ed6337a86ea3.png)

## Version Info

- Version of Majestic: v1.2.24
- Version of Jest: v24.7.1
- Version of Node: v10.8.0
- Operating System: macOS Mojave 10.14.2

**Comment by Raathigesh** [comment]
Is this on every file or on this specific file?

**Comment by mulholio** [comment]
Every file in the project. Does not apply to a new create-react-app on my computer

**Comment by Raathigesh** [comment]
Would you be able to provide a repo where this is reproducible? Need a bit more information to figure out what's going on.

**Comment by mulholio** [comment]
This is occurring on a fairly large, private repo so having some trouble reproducing. I've tried a create-react-app to reproduce but to no avail. Do you have any suspicions about what might be causing it to help point me in the right direction?

**Comment by Raathigesh** [comment]
![image](https://user-images.githubusercontent.com/3108160/55721290-4d252000-5a46-11e9-8d6c-579ee21ed0bf.png)
As soon as you click on a test file, there are few network requests sent. Could you locate the above-mentioned one and verify that you are receiving the names of the test in the response?

The response should be something like where the `name` fields contains the name of the test
![image](https://user-images.githubusercontent.com/3108160/55721371-89f11700-5a46-11e9-8729-9d9bef76f74e.png)

**Comment by TheGallery** [comment]
I have the same problem where some test names are not visible. This is consistently occuring when using template literals instead of regular strings for the name.

**Comment by rahulakrishna** [comment]
@Raathigesh, I figured out the root cause for this issue. The `ast/inspector` expects a `StringLiteral` to parse the names. And gets the value from `path.node.arguments[0].value`. 

For `TemplateLiteral`, Using the `babel/parser`, we're able to get the variable name but not the value of the variable.

`path.node.arguments[0].expressions` give a list of variable names used in the `TemplateLiteral`. 
`path.node.arguments[0].quasis` give a list of hardcoded values in `TemplateLiteral` (eg: `"hello "` in `hello ${name}`)

I need some help to approach this. I'm not familiar with the parser. I see we're using it only to "read code". Would it be possible to execute pieces of code and get those values?

**Comment by rahulakrishna** [comment]
@mulholio , Are you using template literals inside tests? Can you elaborate why you would want template literals. 

Personally, I've always assumed that tests are supposed to have hardcoded names and not dynamic names.

**Comment by Raathigesh** [comment]
Hey @rahulakrishna,

Thanks for digging into this. If you ask me, we don't need to get the variable value, just even displaying the variable name as is (e.g: `hello ${name}`) would be sufficient.
