### ISSUE TITLE
New Release (and auto updates?)

### ISSUE THREAD

**Issue by paulmolluzzo** [Raathigesh/majestic#15]
Thank you for this awesome tool! ❤️ 

## Is this a bug report or a feature request?

🎁  Feature Request

Is it possible to release `master` in the near future? `v0.1.0` has a few issues that are resolved on `master`. #2 is fixed in `master` but not in the download available on the site, so I'm running the dev version for now.

Also, ideally Majestic would automatically check for updates and offer a prompt to download. I haven't used it, but perhaps this package would help with adding that feature? https://github.com/zeit/hazel

## Version Info
N/A

Thank you so much! 🙌

**Comment by Raathigesh** [comment]
The plan is to release a new version end of this weekend. 

Majestic uses https://www.electron.build/ and it supports auto updates without an update server. So when the new released is pushed, Click the link which says "Check for update" in the footer of the sidebar to install the update. Majestic normally checks for update automatically during the initial launch.

But I agree it would be better to have a prominent message or a toast to inform the user about a new update on launch because the current footer link is not good enough to draw any attention. I'll look into it.

Glad you like the tool 👍

**Comment by paulmolluzzo** [comment]
Awesome! Thank you for the response!

**Comment by Raathigesh** [comment]
Will track the enhancement via https://github.com/Raathigesh/majestic/issues/24
