### ISSUE TITLE
Feature: Add CI Support

### ISSUE THREAD

**Issue by amilajack** [Raathigesh/majestic#173]
Currently we're not using any CI. I'm willing to create a PR for this

**Comment by Raathigesh** [comment]
Hey @amilajack 👋,

Thanks for offering to help.

We do have a few integration tests written in Cypress (https://github.com/Raathigesh/majestic/tree/master/integration) and we use GitHub actions to run those tests - https://github.com/Raathigesh/majestic/actions. These tests used to run in Travis but I later moved those to Github since it's easier to manage all in one place.

I think it would be nice to have the GitHub build status badge on the readme.

If you have any other ideas, please do share.
