### ISSUE TITLE
Question about debugging in VSC

### ISSUE THREAD

**Issue by wonskarol** [Raathigesh/majestic#45]
Hey,

Im not sure if I use your VSC plugin correctly. To debug a test, first I have to go to VSC and set breakpoint by myself. Then switch to Majestic, press "Start debugging in VS Code" button, go back to VSC by myself (it doesn't open editor automatically like "open editor and go to this test" button) to eventually debug 😅
I would expect that when I click debug button, VSC opens my test in debug mode with breakpoint set at first assertion. 

Do I miss something or was it so planned? 

BTW. If you go to "show all failures" and try to debug - nothing happens.

**Comment by Raathigesh** [comment]
There are some definite improvements in this workflow.  The major part I wanted to address via the VSC plugin is to remove the hassle of editing the launch config with the test name I want to debug before start debugging.  All the above-mentioned enhancements make sense and I'll have them in the backlog. if you are feeling like contributing, feel free to send  a PR 😄 

"Show all features" debug feature seems like a bug. Will take a look.

**Comment by Raathigesh** [comment]
Hi @wonskarol,

I removed the VS Code integration with the rewrite because its easy to setup a task in vs code to debug the current selected test file and it doesn't make much sense to do it through majestic. But i'm thinking of providing a https://github.com/GoogleChromeLabs/ndb integration so people who don't use vs code can use it. Let me know if you have any thoughts on this.

**Comment by Raathigesh** [comment]
VSCode integration is something I decided to remove with the rewrite so we could focus on the core feature first. Closing this for now.
